services:
  nexus:
    image: double2trouble/nexus:latest
    container_name: nexus
    pull_policy: always
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    volumes:
      - ./nexus:/root/.nexus/
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 2g
    cpus: "2.0"
    healthcheck:
      test: ["CMD", "sh", "-c", "docker logs --since 1m nexus 2>&1 | grep -c 'Failed to receive program message: WebSocket connection closed unexpectedly' | awk '{if ($1 >= 3) exit 1; else exit 0;}'"]
      interval: 5m
      timeout: 10s
      retries: 1
