---
x-defaults:
  &default-service
  pull_policy: always
  restart: unless-stopped
  stop_signal: SIGINT
  tty: true
  logging:
    driver: "json-file"
    options:
      max-size: 1m
      max-file: "1"


services:
  nexus:
    <<: *default-service
    image: double2trouble/nexus:latest
    container_name: nexus
    volumes:
      - ./nexus:/root/.nexus/
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 2g
    cpus: "2.0"
    healthcheck:
      test: ["CMD", "sh", "-c", "docker logs --since 1m nexus 2>&1 | grep -c 'Failed to receive program message: WebSocket connection closed unexpectedly' | awk '{if ($1 >= 3) exit 1; else exit 0;}'"]
      interval: 5m
      timeout: 10s
      retries: 1

  chrome:
    <<: *default-service
    image: kasmweb/chrome:1.16.0
    ports:
      - "3390:6901"
    environment:
      - VNC_PW=${CHROME_VNC_PW}
    volumes:
      - ./chrome_profile:/home/kasm-user/.config

  blockmesh-cli:
    <<: *default-service
    image: dknodes/blockmesh-cli_x86_64:latest
    container_name: blockmesh-cli
    mem_limit: 2g
    cpus: "2.0"
    environment:
      - USER_EMAIL=${BLOCKMSH_USER_EMAIL}
      - USER_PASSWORD=${BLOCKMSH_USER_PASSWORD}
#      OPTIONAL: add some proxy with residental IP if login doesn't work in VPS
#      - HTTP_PROXY=http://127.0.0.1:3128
#      - HTTPS_PROXY=http://127.0.0.1:3128
#      - NO_PROXY=localhost,127.0.0.1

  grass-app:
    <<: *default-service
    image: double2trouble/grass
    environment:
      - NP_TOKEN=${NP_TOKEN_GRASS}
    volumes:
      - ./getgrass/no_proxy.py:/opt/app/no_proxy.py

  nodepay:
    <<: *default-service
    image: kellphy/nodepay
    environment:
      - NP_COOKIE=${NP_COOKIE_NODEPAY}
    stdin_open: true
